apiVersion: aps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-chatbot
  template:
    metadata:
      labels:
        app: rasa-chatbot
    spec:
      containers:
      - name: rasa-chatbot
        image: to_be_created
        ports:
        - containerPorts: 8081