version: '3.0'
services:
  rasa:
    build: 
      context: .
      dockerfile: Dockerfile
    networks: ['rasa-network']
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
  rasa-actions:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    networks: [rasa-network]
    ports:
      - 5055:5055
  
  rasa_ui:
    image: paschmann/rasa-ui:latest
    container_name: rasa_ui
    networks: [rasa-network]
    ports:
      - "5001:5001"
    depends_on:
      - "rasa"
    environment:
      rasa_endpoint: "http://rasa:5050"
networks: {rasa-network: {}}