version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
    restart: always

  rasa-actions:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    networks: [rasa-network]
    ports:
      - 5055:5055
  
  rasa_ui:
    image: paschmann/rasa-ui:latest
    container_name: rasa_ui
    networks: [rasa-network]
    ports:
      - "5001:5001"
    depends_on:
      - "rasa"
    environment:
      rasa_endpoint: "http://rasa:5050"
networks: {rasa-network: {}}



  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: